### PR TITLE
Minecraft 1.19.3

### PR DESCRIPTION
**Pull request by KosmX**

### CODE REVIEW

**Comment by xpple** [comment]
A bunch of stuff was changed, could you maybe explain a bit what you did? In particular the Gradle stuff as I'm very inexperienced with it.

**Comment by KosmX** [comment]
- `gradle/`, `gradlew`, `gradlew.bat` are gradle wrapper  
- gradle shadow plugin `com.github.johnrengelman.shadow` is an advanced tool for creating fat-jar. It can also do basic remapping tasks

- shadowJar task: configure shadowJar to include seedfinding libraries but not the whole minecraft.  
Also I use it to relocate libraries (when creating fatjar, the seedfinding libraries will be in `dev.xpple.seedfinding`)

- remapJar : remap the result of shadowJar, output

**Comment by xpple** [comment]
I'd like to keep the the command trigger. It's for a chat feature that allows code to be run by commands (but it's unused now).

**Comment by KosmX** [comment]
I don't really understand what is that supposed to do, but it is unused and broken in 1.19.2...

Also, I can not refactor it to work in 1.19.3 until I understand its purpose.

**Comment by xpple** [comment]
Could you remove the `mod_version=1.5.8` change? I will change some other stuff before bumping the version.

**Comment by xpple** [comment]
Thank you!

**Pull request merged**
