### PR TITLE
CI: Add release workflow

### PR DESCRIPTION
**Pull request by networkException**
This adds a github actions workflow that automatically publishes
a new release with a build jar file when a git tag gets pushed

### CODE REVIEW

**Comment by networkException** [comment]
A release looks something like this for reference https://github.com/networkException/SeedMapper/releases/tag/test2

**Comment by xpple** [comment]
Will they be shown separately from manual releases? And would it be possible to mark these automated releases as a pre-release?

**Comment by networkException** [comment]
Their author is github actions as you can see, but sure I can change it to a pre-release

**Comment by networkException** [comment]
I updated this branch, the pre-release would look like this https://github.com/networkException/SeedMapper/releases/tag/test3

**Comment by xpple** [comment]
It seems like I misunderstood part of this commit. I initially thought it would publish a release/tag on every commit (which is why I asked for the pre-release mark), but it only seems to do so when a new tag is created.
Currently I add a changelog to every release I publish, along with some info about the mod's compatibility. I do this all manually though GitHub. Would it be possible to have this script add the JAR to a manually created release?

**Comment by networkException** [comment]
The workflow now adds a jar asset to a release after it has been created manually. Additionally, the file now gets hashed in the workflow so that users who downloaded it can verify that it hasn't been modified since it left github actions

**Comment by xpple** [comment]
Looks good to me, thanks!

**Pull request merged**
